config/routes.rb
PeaceCorpsAfrica::Application.routes.draw do

  resources :references

  resources :valid_emails, :except => [:show]

  resources :revisions, :only => [:destroy]

  resources :pages do
    resources :revisions, :except => [:destroy]
  end

  resources :initiatives

  resources :countries

  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  
  devise_for :users
  
  resources :users, :only => [:show, :index]

  namespace :initiative, :path => '/:abbreviation', :constraints => { :abbreviation => /[a-z]{3,7}/i } do
    resources :countries
    get '/' => 'home#index', :as => :home
  end

  namespace :country, :path => '/:country_code', :constraints => { :country_code => /[a-z]{2}/i } do
    resources :initiatives
    get '/' => 'home#index', :as => :home
  end

end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
  
  attr_accessible :name, :page_id, :start_date, :contact_email, :site_url, :donate_url, :country_initiatives_attributes, :abbreviation

  belongs_to :page

  has_many :country_initiatives, :dependent => :destroy
  has_many :countries, :through => :country_initiatives

  # requires name, start_date, abbreviation
  validates :name, :abbreviation, :page_id, :presence => true
  validates :name, :contact_email, :site_url, :donate_url, :length => { :maximum => 255 }
  validates :abbreviation, :length => { :minimum => 3, :maximum => 7 }, :uniqueness => true, :alphanumeric => true
  validates :name, :uniqueness => true
  validates :contact_email, :email => true, :allow_blank => true
  validates :page_id, :numericality => { :only_integer => true }
  validates :start_date, :date => true
  validates :donate_url, :site_url, :url => true, :allow_blank => true

  before_validation :do_before_validation
  before_save :do_before_save

  accepts_nested_attributes_for :country_initiatives, :allow_destroy => true

  default_scope :order => 'name ASC'

  def initiative_url_for(country)
    country_initiatives.find_by_country_id(country.id).initiative_url
  end

  def to_param
    abbreviation.downcase
  end

  private

    def do_before_validation
      self.start_date = start_date.to_date unless start_date.blank?
    end

    def do_before_save
      self.abbreviation = abbreviation.upcase
    end

end

app/controllers/country/initiatives_controller.rb
class Country::InitiativesController < ApplicationController
  authorize_resource

  def index
    @country = Country.find_by_code(params[:country_code].upcase)
    @initiatives = @country.initiatives
    render :text => 'initiatives/index'
  end

  def show
    @country = Country.find_by_code(params[:country_code].upcase)
    @initiative = @country.initiatives.find_by_abbreviation(params[:id].upcase)
    render :text => "#{@country.name} -> #{@initiative.name}"
  end

end

app/controllers/initiative/countries_controller.rb
class Initiative::CountriesController < ApplicationController
  authorize_resource

  def index
    @initiative = Initiative.find_by_abbreviation(params[:abbreviation].upcase)
    @countries = @initiative.countries
    render :text => 'countries/index'
  end

  def show
    @initiative = Initiative.find_by_abbreviation(params[:abbreviation].upcase)
    @country = Country.find_by_code(params[:id].upcase)
    render :text => "#{@initiative.name} -> #{@country.name}"
  end

end

app/controllers/initiative/home_controller.rb
class Initiative::HomeController < ApplicationController
  skip_authorization_check

  def index
    @users = User.all
    @initiative = Initiative.find_by_abbreviation(params[:abbreviation].upcase)
  end
end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController
  authorize_resource

  # GET /initiatives
  # GET /initiatives.json
  def index
    @initiatives = Initiative.all
    @countries = Country.all

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  # GET /initiatives/1
  # GET /initiatives/1.json
  def show
    @initiative = Initiative.find_by_abbreviation(params[:id].upcase)
    @page = @initiative.page

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end

  # GET /initiatives/new
  # GET /initiatives/new.json
  def new
    @initiative = Initiative.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @initiative }
    end
  end

  # GET /initiatives/1/edit
  def edit
    @initiative = Initiative.find_by_abbreviation(params[:id].upcase)
  end

  # POST /initiatives
  # POST /initiatives.json
  def create
    @initiative = Initiative.new(params[:initiative])

    respond_to do |format|
      if @initiative.save
        format.html { redirect_to edit_initiative_path(@initiative), notice: 'Initiative was successfully created.' }
        format.json { render json: @initiative, status: :created, location: @initiative }
      else
        format.html { render action: "new" }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /initiatives/1
  # PUT /initiatives/1.json
  def update
    @initiative = Initiative.find_by_abbreviation(params[:id].upcase)

    respond_to do |format|
      if @initiative.update_attributes(params[:initiative])
        format.html { redirect_to @initiative, notice: 'Initiative was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /initiatives/1
  # DELETE /initiatives/1.json
  def destroy
    @initiative = Initiative.find_by_abbreviation(params[:id].upcase)
    @initiative.destroy

    respond_to do |format|
      format.html { redirect_to initiatives_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/initiatives_helper.rb
module InitiativesHelper
end

app/views/initiatives/_form.html.haml
= nested_form_for @initiative, :html => { :class => 'form-horizontal' } do |f|
  -if @initiative.errors.any?
    #error_explanation
      %h2= "#{pluralize(@initiative.errors.count, "error")} prohibited this initiative from being saved:"
      %ul
        - @initiative.errors.full_messages.each do |msg|
          %li= msg
  %legend Initiative Info
  = render 'shared/form_info'
  .control-group
    %label.control-label Initiative Name
    .controls
      = f.text_field :name, :class => 'required'
  .control-group
    %label.control-label Abbreviated Name
    .controls
      = f.text_field :abbreviation, :class => 'required'
      %span.help-inline 3-7 chars, no spaces
  .control-group
    %label.control-label Starting Date
    .controls
      = f.text_field :start_date, :class => 'datepicker required'
      %span.help-inline yyyy-mm-dd
  .control-group
    %label.control-label Default Page
    .controls
      = f.collection_select :page_id, Page.all, :id, :title, {}, {:class => 'required'}
  .control-group
    %label.control-label Contact Email
    .controls
      = f.text_field :contact_email
  .control-group
    %label.control-label Site URL
    .controls
      = f.text_field :site_url
      %span.help-inline http://example.url
  .control-group
    %label.control-label Donate URL
    .controls
      = f.text_field :donate_url
      %span.help-inline http://example.url
  %legend Countries
  - if f.object.new_record?
    .alert Once you've created the initiative and at least one country, you can come back and add countries.
  - elsif !Country.any?
    .alert You must #{link_to 'create countries', new_country_path} before adding them to initiatives
  - else
    = render 'country_initiatives/help_text'
    = f.fields_for :country_initiatives do |ff|
      .control-group
        %label.control-label Country/Join date
        .controls
          = ff.collection_select :country_id, Country.all, :id, :name, {}, {:class => 'span2 required'}
          = ff.text_field :join_date, :class => 'span2 datepicker'
          = ff.link_to_remove raw('<span class="icon-minus"></span>'), :class => 'btn btn-mini btn-danger'
      = render 'country_initiatives/shared_fields', :f => ff
      %hr
    = f.link_to_add :country_initiatives, :class => 'btn btn-mini btn-success' do
      %span.icon-plus
      add a country
  .form-actions
    = f.submit 'Save', :class => 'btn btn-primary'
    = link_to 'Cancel', initiatives_path, :class => 'btn'

app/views/initiatives/_menu.html.haml
.container
  .row
    .span12
      - if @initiative && can?(:edit, @initiative)
        .subnav
          %ul.nav.nav-pills.pull-right
            %li.dropdown
              %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
                Actions
                %b.caret
              %ul.dropdown-menu.pull-right
                %li
                  = link_to edit_initiative_path(@initiative) do
                    %span.icon-pencil
                    Edit #{@initiative.name}
                - if can? :create, Initiative
                  %li.divider
                  %li
                    = link_to new_initiative_path do
                      %span.icon-plus
                      New Initiative
                - if can? :read, @initiative.page
                  %li.divider
                  %li
                    = link_to @initiative.page do
                      %span.icon-list-alt
                      View Page
                - if can? :edit, @initiative.page
                  %li
                    = link_to edit_page_path(@initiative.page) do
                      %span.icon-pencil
                      Edit Page

app/views/initiatives/edit.html.haml
.container
  .row
    .span9
      .hero-unit.red
        %h1 Edit #{@initiative.name}
  .row
    .span6.offset3
      = render 'form'

app/views/initiatives/index.html.haml
:plain
  <!--Load the AJAX API-->
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
:javascript
  // Load the Visualization API and the piechart package.
  google.load('visualization', '1.0', {'packages':['geochart']});

  // Set a callback to run when the Google Visualization API is loaded.
  google.setOnLoadCallback(drawChart);

  // Callback that creates and populates a data table, instantiates the pie chart, 
  // passes in the data and draws it.
  function drawChart() {
  
    // pull the json data from the app/source
    var jsonGeoData  = $.ajax({
      url:'#{initiatives_path(:format => :json)}',
      dataType:'json',
      async:false
      }).responseText;

    // set the options
    var geoOptions = {
      'backgroundColor': { fill: 'white', stroke: '#666', strokeWidth: 0 },
      'region': '002',
      // colors are gray, $btnInfoBackground, spin($btnPrimaryBackground, 15%)
      'colorAxis': {minValue: 0, maxValue: #{Initiative.count}, values: [0,1,#{Initiative.count}], colors: ['#666', '#5bc0de', '#05c']},
      //'colorAxis': {minValue: 2011, maxValue: 2012, values: [2011,2012], colors: ['#FF0000', '#00FF00']},
      'datalessRegionColor': '#f5f5f5',
      'height': 'auto',
      'keepAspectRatio': true,
      'legend': 'none',//{numberFormat: '', textStyle: {color:'black'}},
      'resolution': 'countries',
      'width': '100%',
      'tooltip': {color: 'black'}
    };

    // load the json data source into a datatable for the chart
    var geoData = new google.visualization.DataTable(jsonGeoData);

    // set the chart target div
    var geo_chart = new google.visualization.GeoChart(document.getElementById('chart_div_geo'));

    // Every time the geo chart fires the "regionClick" event, it should call our
    // selectHandler() function.
    google.visualization.events.addListener(geo_chart, 'regionClick', selectHandler);
  
    geo_chart.draw(geoData, geoOptions);
    function selectHandler(e) {
      //alert(countries[e.region.toLowerCase()]);
      var country_id = $.trim($.ajax({url:'/countries/' + e.region + '.json', dataType:'text', async:false}).responseText);
      //alert('/countries/' + country_id);
      if (country_id && country_id != 'null') {
        window.location = '/countries/' + e.region;
        //alert('"'+country_id+'"');
      }
    }
  }

.container-fluid
  .row-fluid
    .span3
      .well.blue
        %h1 What are we up to?
        %p Peace Corps has initiated #{pluralize(@initiatives.count, 'important continent-wide initiative')} in Africa.  Volunteers work with partners in the following initiatives:
      %ul.nav.nav-tabs.nav-stacked
        - for initiative in @initiatives do
          %li
            = link_to initiative do
              %span.icon-arrow-right
              = initiative.name
    .span9
      #chart_div_geo

app/views/initiatives/index.json.haml
:erb
  {
    "cols": [
        {
            "id": 0,
            "label": "Country",
            "type": "string"
        },
        {
            "id": 1,
            "label": "Initiatives",
            "type": "number"
        }
    ],
    "rows": [
      <% for country in @countries do %>
        {
          "c": [
              {
                  "v": "<%= country.name %>"
              },
              {
                  "v": <%= country.initiatives.count %>
              }
          ]
        }<%= ',' unless country == @countries.last %>
      <% end %>
    ]
  }

app/views/initiatives/new.html.haml
.container
  .row
    .span9
      .hero-unit.blue
        %h1 Add New Initiative
  .row
    .span6.offset3
      = render 'form'

app/views/initiatives/show.html.haml
.container
  .row
    .span12
      .hero-unit.green
        %h1
          #{@initiative.name}
          %small a Peace Corps Initiative.
  .row
    .span2.hide-overflow
      - unless @initiative.contact_email.blank?
        %h3 Contact
        %address
          %strong
            = link_to @initiative.contact_email, "mailto:#{@initiative.contact_email}"
      &nbsp;
    .span6
      = raw @page.html
    .span4
      %ul.nav.nav-tabs.nav-stacked
        - if @initiative.site_url.blank?
          %li= link_to "Visit #{@initiative.name}", initiative_home_path(@initiative)
        - else
          %li= link_to "Visit #{@initiative.name}", @initiative.site_url, :target => '_blank'
        %li= link_to 'Donate', @initiative.donate_url, :target => '_blank' unless @initiative.donate_url.blank?
        - for country in @initiative.countries do
          %li= link_to "#{@initiative.name} in #{country.name}", (@initiative.initiative_url_for(country).blank? ? country_initiative_path(country, @initiative) : @initiative.initiative_url_for(country))
        %li= link_to 'View All Countries', countries_path
  .row
    .span12
      %ul.thumbnails
        %li.span4= link_to image_tag('http://static.pcsenegal.org/photos/ag1-370x250.jpg'), countries_path, :class => 'thumbnail'
        %li.span4= link_to image_tag('http://static.pcsenegal.org/photos/ag3-370x250.jpg'), countries_path, :class => 'thumbnail'
        %li.span4= link_to image_tag('http://static.pcsenegal.org/photos/ag4-370x250.jpg'), countries_path, :class => 'thumbnail'

app/views/initiatives/show.json.haml
:erb
  {
    "cols": [
        {
            "id": 0,
            "label": "Country",
            "type": "string"
        },
        {
            "id": 1,
            "label": "Join date",
            "type": "number"
        }
    ],
    "rows": [
        <% for country in @initiative.countries do %>
          {
            "c": [
                {
                    "v": "<%= country.name %>"
                },
                {
                    "v": <%= country.join_date(@initiative).to_time.to_i %>
                }
            ]
          }<%= ',' unless country == @initiative.countries.last %>
        <% end %>
    ]
  }