config/routes.rb
PeaceCorpsAfrica::Application.routes.draw do

  resources :references

  resources :valid_emails, :except => [:show]

  resources :revisions, :only => [:destroy]

  resources :pages do
    resources :revisions, :except => [:destroy]
  end

  resources :initiatives

  resources :countries

  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  
  devise_for :users
  
  resources :users, :only => [:show, :index]

  namespace :initiative, :path => '/:abbreviation', :constraints => { :abbreviation => /[a-z]{3,7}/i } do
    resources :countries
    get '/' => 'home#index', :as => :home
  end

  namespace :country, :path => '/:country_code', :constraints => { :country_code => /[a-z]{2}/i } do
    resources :initiatives
    get '/' => 'home#index', :as => :home
  end

end

app/models/reference.rb
class Reference < ActiveRecord::Base
  attr_accessible :link_source_id, :link_source_type, :link_target_id, :link_target_type, :link_text

  belongs_to :link_target, :polymorphic => true
  belongs_to :link_source, :polymorphic => true

  validates :link_text, :presence => true, :length => { :maximum => 255 }
  validates :link_source_id, :link_source_type, :presence => true

  default_scope :order => 'link_text ASC'
  scope :to_pages, where(:link_target_type => 'Page')

  def self.process_string(original, source_class, source_id)
    original.gsub(/(\[([a-z]*)\[((https*:\/\/)*[^\[]+)\]\])/) do |match|
      if $4.blank?
        if $2 == 'user'
          target = 'User'
          results = User.where("UPPER(name) LIKE UPPER(?)", "%#{$3}%")
        else
          target = 'Page'
          results = Page.where("UPPER(title) LIKE UPPER(?)", "%#{$3}%")
        end
          
        Reference.create!(
          :link_source_id => source_id, 
          :link_source_type => source_class,
          :link_text => $3,
          :link_target_type => target,
          :link_target_id => (results.any? ? results.first.id : nil)
        )

        # if there are no results, set the missing link
        if results.count < 1
          "<a class=\"missing\" href=\"/#{target.parameterize.pluralize}\">#{$3}<span class=\"icon-remove-circle\"></span></a>"
        # if there are more than 1 result, link to disambiguation
        elsif results.count > 1
          "<a class=\"disambiguation\" href=\"/#{target.parameterize.pluralize}\">#{$3}<span class=\"icon-random\"></span></a>"
        # if there is only one result, link there
        else
          "<a href=\"/#{target.parameterize.pluralize}/#{results.first.to_param}\">#{$3}</a>"
        end
      else
        Reference.create!(
          :link_source_id => source_id, 
          :link_source_type => source_class,
          :link_text => $3
        )
        "<a href=\"#{$3}\">#{$3}</a>"
      end
    end
  end

end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  load_and_authorize_resource

  # GET /references
  # GET /references.json
  def index
    @references = Reference.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @references }
    end
  end

  # GET /references/1
  # GET /references/1.json
  def show
    @reference = Reference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reference }
    end
  end

  # GET /references/new
  # GET /references/new.json
  def new
    @reference = Reference.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reference }
    end
  end

  # GET /references/1/edit
  def edit
    @reference = Reference.find(params[:id])
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(params[:reference])

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render json: @reference, status: :created, location: @reference }
      else
        format.html { render action: "new" }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /references/1
  # PUT /references/1.json
  def update
    @reference = Reference.find(params[:id])

    respond_to do |format|
      if @reference.update_attributes(params[:reference])
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference = Reference.find(params[:id])
    @reference.destroy

    respond_to do |format|
      format.html { redirect_to references_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_form.html.haml
= form_for @reference do |f|
  -if @reference.errors.any?
    #error_explanation
      %h2= "#{pluralize(@reference.errors.count, "error")} prohibited this reference from being saved:"
      %ul
        - @reference.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :link_id
    = f.number_field :link_id
  .field
    = f.label :link_type
    = f.text_field :link_type
  .field
    = f.label :link_text
    = f.text_field :link_text
  .actions
    = f.submit 'Save'

app/views/references/edit.html.haml
%h1 Editing reference

= render 'form'

= link_to 'Show', @reference
\|
= link_to 'Back', references_path

app/views/references/index.html.haml
%h1 Listing references

%table
  %tr
    %th Link source
    %th Link target
    %th
    %th
    %th

  - @references.each do |reference|
    %tr
      %td= reference.link_source.title
      %td= reference.link_target.title
      %td= link_to 'Show', reference
      %td= link_to 'Edit', edit_reference_path(reference)
      %td= link_to 'Destroy', reference, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Reference', new_reference_path

app/views/references/new.html.haml
%h1 New reference

= render 'form'

= link_to 'Back', references_path

app/views/references/show.html.haml
%p#notice= notice

%p
  %b Link:
  = @reference.link_id
%p
  %b Link type:
  = @reference.link_type
%p
  %b Link text:
  = @reference.link_text

= link_to 'Edit', edit_reference_path(@reference)
\|
= link_to 'Back', references_path