config/routes.rb
PeaceCorpsAfrica::Application.routes.draw do

  resources :references

  resources :valid_emails, :except => [:show]

  resources :revisions, :only => [:destroy]

  resources :pages do
    resources :revisions, :except => [:destroy]
  end

  resources :initiatives

  resources :countries

  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  
  devise_for :users
  
  resources :users, :only => [:show, :index]

  namespace :initiative, :path => '/:abbreviation', :constraints => { :abbreviation => /[a-z]{3,7}/i } do
    resources :countries
    get '/' => 'home#index', :as => :home
  end

  namespace :country, :path => '/:country_code', :constraints => { :country_code => /[a-z]{2}/i } do
    resources :initiatives
    get '/' => 'home#index', :as => :home
  end

end

app/models/country.rb
class Country < ActiveRecord::Base

  attr_accessible :code, :name, :page_id, :active, :contact_email, :site_url, :donate_url, :start_date, :country_initiatives_attributes, :info_url

  belongs_to :page

  has_many :country_initiatives, :dependent => :destroy
  has_many :initiatives, :through => :country_initiatives

  # required: name, start_date
  validates :name, :code, :page_id, :presence => true
  validates :name, :contact_email, :site_url, :donate_url, :length => { :maximum => 255 }
  validates :code, :length => { :minimum => 2, :maximum => 2 }, :uniqueness => true
  validates :start_date, :date => true
  validates :contact_email, :email => true, :allow_blank => true
  validates :donate_url, :site_url, :info_url, :url => true, :allow_blank => true
  validates :page_id, :numericality => { :only_integer => true }
  validates :code, :iso2 => true

  before_validation :do_before_validation
  before_save :do_before_save

  accepts_nested_attributes_for :country_initiatives, :allow_destroy => true

  default_scope order('name ASC')
  scope :active, where(:active => true)

  def join_date(initiative)
    country_initiatives.where(:initiative_id => initiative.id).limit(1).first.join_date
  end

  def country_url_for(initiative)
    country_initiatives.where(:initiative_id => initiative.id).limit(1).first.country_url
  end

  def to_param
    code.downcase
  end

  private

    def do_before_validation
      self.name = Carmen.country_name(code)
      #self.start_date = start_date.to_date unless start_date.blank?
    end

    def do_before_save
      self.code = code.upcase
    end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  authorize_resource

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
    @country = Country.find_by_code(params[:id].upcase)
    @page = @country.page

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @country }
    end
  end

  # GET /countries/new
  # GET /countries/new.json
  def new
    @country = Country.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @country }
    end
  end

  # GET /countries/1/edit
  def edit
    @country = Country.find_by_code(params[:id].upcase)
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(params[:country])

    respond_to do |format|
      if @country.save
        format.html { redirect_to edit_country_path(@country), notice: 'Country was successfully created.' }
        format.json { render json: @country, status: :created, location: @country }
      else
        format.html { render action: "new" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /countries/1
  # PUT /countries/1.json
  def update
    @country = Country.find_by_code(params[:id].upcase)

    respond_to do |format|
      if @country.update_attributes(params[:country])
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country = Country.find_by_code(params[:id].upcase)
    @country.destroy

    respond_to do |format|
      format.html { redirect_to countries_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/country/home_controller.rb
class Country::HomeController < ApplicationController
  skip_authorization_check

  def index
    @users = User.all
    @country = Country.find_by_code(params[:country_code].upcase)
  end
end

app/controllers/country/initiatives_controller.rb
class Country::InitiativesController < ApplicationController
  authorize_resource

  def index
    @country = Country.find_by_code(params[:country_code].upcase)
    @initiatives = @country.initiatives
    render :text => 'initiatives/index'
  end

  def show
    @country = Country.find_by_code(params[:country_code].upcase)
    @initiative = @country.initiatives.find_by_abbreviation(params[:id].upcase)
    render :text => "#{@country.name} -> #{@initiative.name}"
  end

end

app/controllers/initiative/countries_controller.rb
class Initiative::CountriesController < ApplicationController
  authorize_resource

  def index
    @initiative = Initiative.find_by_abbreviation(params[:abbreviation].upcase)
    @countries = @initiative.countries
    render :text => 'countries/index'
  end

  def show
    @initiative = Initiative.find_by_abbreviation(params[:abbreviation].upcase)
    @country = Country.find_by_code(params[:id].upcase)
    render :text => "#{@initiative.name} -> #{@country.name}"
  end

end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.haml
= nested_form_for @country, :html => {:class => 'form-horizontal'} do |f|
  = render 'shared/form_errors', :item => @country if @country.errors.any?
  %legend Country Info
  = render 'shared/form_info'
  .control-group
    %label.control-label Country Name
    .controls
      = f.country_select :code, nil, {}, {:class => 'required'}
  .control-group
    %label.control-label Peace Corps Start Date
    .controls
      = f.text_field :start_date, :class => 'datepicker required'
      %span.help-inline
        %code yyyy-mm-dd
  .control-group
    %label.control-label Default Page
    .controls
      = f.collection_select :page_id, Page.all, :id, :title, {}, {:class => 'required'}
  .control-group
    %label.control-label Contact Email
    .controls
      = f.text_field :contact_email
  .control-group
    %label.control-label Info URL
    .controls
      = f.text_field :info_url
      %span.help-inline PC Page, http://example.url
  .control-group
    %label.control-label Site URL
    .controls
      = f.text_field :site_url
      %span.help-inline http://example.url
  .control-group
    %label.control-label Donate URL
    .controls
      = f.text_field :donate_url
      %span.help-inline http://example.url
  .control-group
    %label.control-label Active
    .controls
      = f.check_box :active
      %span.help-inline Is this country currently open?
  %legend Initiatives
  - if f.object.new_record?
    .alert Once you've created the country and at least one initiative, you can come back and add initiatives.
  - elsif !Initiative.any?
    .alert You must #{link_to 'create initiatives', new_initiative_path} before adding them to countries.
  - else
    = render 'country_initiatives/help_text'
    = f.fields_for :country_initiatives do |ff|
      .control-group
        %span.control-label Initiative/Join Date
        .controls
          = ff.collection_select :initiative_id, Initiative.all, :id, :name, {}, {:class => 'span2 required'}
          = ff.text_field :join_date, :class => 'span2 datepicker'
          = ff.link_to_remove raw('<span class="icon-minus"></span>'), :class => 'btn btn-mini btn-danger'
      = render 'country_initiatives/shared_fields', :f => ff
      %hr
    = f.link_to_add :country_initiatives, :class => 'btn btn-mini btn-success' do
      %span.icon-plus
      add an initiative
  .control-group
    .controls
      = f.submit 'Save', :class => 'btn btn-primary'

app/views/countries/_menu.html.haml
.container
  .row
    .span12
      - if @country && can?(:edit, @country)
        .subnav
          %ul.nav.nav-pills.pull-right
            %li.dropdown
              %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
                Actions
                %b.caret
              %ul.dropdown-menu.pull-right
                %li
                  = link_to edit_country_path(@country) do
                    %span.icon-pencil
                    Edit #{@country.name}
                - if can? :create, Country
                  %li.divider
                  %li
                    = link_to new_country_path do
                      %span.icon-plus
                      New Country
                - if can? :read, @country.page
                  %li.divider
                  %li
                    = link_to @country.page do
                      %span.icon-list-alt
                      View Page
                - if can? :edit, @country.page
                  %li
                    = link_to edit_page_path(@country.page) do
                      %span.icon-pencil
                      Edit Page

app/views/countries/edit.html.haml
.container
  .row
    .span9
      .hero-unit.orange
        %h1 Edit #{@country.name}
  .row
    .span6.offset3
      = render 'form'

app/views/countries/index.html.haml
:plain
  <!--Load the AJAX API-->
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
:javascript
  // Load the Visualization API and the piechart package.
  google.load('visualization', '1.0', {'packages':['geochart']});

  // Set a callback to run when the Google Visualization API is loaded.
  google.setOnLoadCallback(drawChart);

  // Callback that creates and populates a data table, instantiates the pie chart, 
  // passes in the data and draws it.
  function drawChart() {
  
    // pull the json data from the app/source
    var jsonGeoData  = $.ajax({
      url:'#{params[:abbreviation] ? initiative_countries_path(:abbreviation => 'stomp', :format => :json) : countries_path(:format => :json)}',
      dataType:'json',
      async:false
      }).responseText;

    // set the options
    var geoOptions = {
      'backgroundColor': { fill: 'white', stroke: '#666', strokeWidth: 0 },
      'region': '002',
      // colors are $orange, $btnInfoBackground, spin($btnPrimaryBackground, 15%)
      'colorAxis': {colors: ['#5bc0de', '#05c']},
      //'colorAxis': {minValue: 0, maxValue: 300, values: [0,1,300], colors: ['#f89406', '#5bc0de', '#05c']},
      //'colorAxis': {minValue: 2011, maxValue: 2012, values: [2011,2012], colors: ['#FF0000', '#00FF00']},
      'datalessRegionColor': '#f5f5f5',
      'height': 'auto',
      'keepAspectRatio': true,
      'legend': {numberFormat: '####', textStyle: {color:'black'}},
      'resolution': 'countries',
      'width': '100%',
      'tooltip': {color: 'black'}
    };

    // load the json data source into a datatable for the chart
    var geoData = new google.visualization.DataTable(jsonGeoData);

    // set the chart target div
    var geo_chart = new google.visualization.GeoChart(document.getElementById('chart_div_geo'));

    // Every time the geo chart fires the "regionClick" event, it should call our
    // selectHandler() function.
    google.visualization.events.addListener(geo_chart, 'regionClick', selectHandler);
  
    geo_chart.draw(geoData, geoOptions);
    function selectHandler(e) {
      //alert(countries[e.region.toLowerCase()]);
      var country_id = $.trim($.ajax({url:'/countries/' + e.region + '.json', dataType:'text', async:false}).responseText);
      //alert('/countries/' + country_id);
      if (country_id && country_id != 'null') {
        window.location = '/countries/' + e.region;
        //alert('"'+country_id+'"');
      }
    }
  }

.container-fluid
  .row-fluid
    .span3
      .well.green
        %h1 Where to now?
        %p Currently, the Peace Corps Africa region has Volunteers serving in #{pluralize(Country.active.count, 'nation')}.
        %p Peace Corps has suspended operations for security reasons in Mali and Niger.
        %p For more information about Peace Corps Africa programs, past and present, visit the #{link_to 'Peace Corps agency web site', 'http://www.peacecorps.gov/learn/wherepc/africa/', :target => '_blank'}.
      %ul.nav.nav-tabs.nav-stacked
        - for country in @countries do
          %li
            = link_to country do
              %span.icon-arrow-right
              = country.name
    .span9
      #chart_div_geo

app/views/countries/index.json.haml
:erb
  {
    "cols": [
        {
            "id": 0,
            "label": "Country",
            "type": "string"
        },
        {
            "id": 1,
            "label": "Year",
            "type": "number"
        }
    ],
    "rows": [
        <% for country in @countries do %>
          {
            "c": [
                {
                    "v": "<%= country.name %>"
                },
                {
                    "v": <%= country.start_date.year %>
                }
            ]
          }<%= ',' unless country == @countries.last %>
        <% end %>
    ]
  }

app/views/countries/new.html.haml
.container
  .row
    .span9
      .hero-unit.green
        %h1 Add a country
  .row
    .span6.offset3
      = render 'form'

app/views/countries/show.html.haml
.container
  .row
    .span12
      .hero-unit.blue
        %h1
          #{@country.name}.
          %small Since #{@country.start_date.year}.
  .row
    .span2
      - unless @country.contact_email.blank?
        %h3 Contact
        %address
          %strong= @country.contact_email
      &nbsp;
    .span6
      = raw @page.html
    .span4
      %ul.nav.nav-tabs.nav-stacked
        %li
          - if @country.site_url.blank?
            = link_to "Visit Peace Corps | #{@country.name}", country_home_path(@country)
          - else
            = link_to "Visit Peace Corps | #{@country.name}", @country.site_url, :target => '_blank'
        %li= link_to 'Donate', @country.donate_url, :target => '_blank' unless @country.donate_url.blank?
        - for initiative in @country.initiatives do
          %li= link_to "#{initiative.name} in #{@country.name}", (@country.country_url_for(initiative).blank? ? country_initiative_path(@country, initiative) : @country.country_url_for(initiative))
        %li= link_to 'View All Initiatives', initiatives_path
  .row
    .span12
      %ul.thumbnails
        %li.span4= link_to image_tag('http://static.pcsenegal.org/photos/ag1-370x250.jpg'), countries_path, :class => 'thumbnail'
        %li.span4= link_to image_tag('http://static.pcsenegal.org/photos/ag3-370x250.jpg'), countries_path, :class => 'thumbnail'
        %li.span4= link_to image_tag('http://static.pcsenegal.org/photos/ag4-370x250.jpg'), countries_path, :class => 'thumbnail'